version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gestalt
    versions:
    - 17.5.5
    - 17.6.1
    - 17.6.2
    - 17.6.3
    - 17.7.0
    - 18.0.0
    - 18.1.2
    - 19.1.1
    - 19.1.2
    - 19.2.0
    - 19.2.2
    - 20.0.2
    - 20.1.1
    - 20.1.2
    - 20.1.3
    - 20.2.1
    - 20.3.3
    - 21.0.1
    - 21.0.3
    - 21.0.5
    - 21.0.6
    - 21.1.0
    - 21.2.1
    - 21.3.1
    - 21.4.3
    - 21.4.4
    - 21.4.7
    - 21.5.0
    - 21.5.1
    - 21.6.2
    - 21.6.3
    - 21.6.5
    - 21.7.1
    - 21.7.2
    - 21.7.7
    - 21.8.0
    - 21.8.1
    - 21.8.2
  - dependency-name: react-scripts
    versions:
    - 4.0.2
